import type { Config } from "tailwindcss";

export default <Partial<Config>>{
  darkMode: ["class", '[data-mode="dark"]'],
  theme: {
    fontSize: {
      xs: "0.75rem",
      sm: "0.9rem",
      base: "1rem",
      lg: "1.125",
      xl: "1.25rem",
      "2xl": "1.5rem",
      "3xl": "1.7rem",
      "4xl": "2rem",
      "5xl": "3rem",
      "6xl": "3.75rem",
      "7xl": "4.5rem",
      "8xl": "6rem",
      "9xl": "8rem",
      "10xl": ["11rem", "12rem"],
    },
    colors: {
      transparent: "transparent",
      current: "currentColor",
      white: "#ffffff",
      black: "#00000",
      "copy-black": "#231F20",
      "galaxy-blue": "#000735",
      "rose-quartz": "#eab8b2",
      "purple-rain": "#440B45",
      "classic-blue": "#0f4c81",
      "orange-red": "#DD5928",
      "chive-green": "#00966d",
      "biscay-green": "#00b3b0",
      "purbeck-stone": "#e3d9d7",
      "light-yellow": "#f9e79f",
    },
  },
  plugins: [],
  content: [
    "components/**/*.{vue,js,ts}",
    "layouts/**/*.vue",
    "pages/**/*.vue",
    "composables/**/*.{js,ts}",
    "plugins/**/*.{js,ts}",
    "utils/**/*.{js,ts}",
    "App.{js,ts,vue}",
    "app.{js,ts,vue}",
    "Error.{js,ts,vue}",
    "error.{js,ts,vue}",
    "app.config.{js,ts}",
  ],
};
